### ISSUE TITLE
Getting spam from noreply@cant-not-tweet-this.com

### ISSUE THREAD

**Issue by fob-mobility** [tholman/cant-not-tweet-this#2]
Might want to check if you are compromised, maybe take down old funny sites instead of letting them become tools used for crime.

**Comment by tholman** [comment]
It's a static site on netlify dns with no mail server, just regular internet domain spoofing spam.

Old funny sites should live forever, the second I let this domain expire it would be bought by some spam robot pushing gambling crap like so many of the fun fallen sites of the past.
